clear; clc;
filename = 'CN1_50n1_250N2_0n2_0N3_0n3_0z_50NAll_12500crosslinkfinal.ord';
outputname = ['pdms_' filename(1:end-4) '.data'];
ranDeflection = 0.2;
data = readmatrix(filename,"FileType","text");
[Natom, column] = size(data);
Tatom = 1;
group = (column - 5)/2;
xyz = data(:,1:3);
% ===== 随机球面扰动（半径 r）=====
r = 0.2;   % 你可以改，要求 r < 1

% 生成随机方向（高斯分布）
rand_vec = randn(Natom, 3);

% 归一化到单位球面
norms = sqrt(sum(rand_vec.^2, 2));
unit_vec = rand_vec ./ norms;

% 乘以半径 r，得到球面上的点
displacement = r * unit_vec;

% 更新坐标
xyz = xyz + displacement;

xyz = 4.48 / 2 * xyz;
xlo = min(xyz(:,1));
xhi = max(xyz(:,1));
ylo = min(xyz(:,2));
yhi = max(xyz(:,2));
zlo = min(xyz(:,3));
zhi = max(xyz(:,3));
atomID = 1:Natom;
atomID = atomID(:);
atomType = ones([Natom,1]);
atomCharge = zeros([Natom,1]);
molemerID = data(:,end);
Atoms = [atomID, atomType, atomType, atomCharge, xyz];

% 获取bond信息
bondList = [];
bondID = 1;
for i = 1:Natom
    % 官能团连接列起始位置
    conn_start = 5 + group; 
    
    for g = 1:group
        j = data(i, conn_start + g - 1);
        
        if j > 0 && j > i   % 防止重复
            bondList(end+1,:) = [bondID, 1, i, j];
            bondID = bondID + 1;
        end
    end
end
Nbond = size(bondList,1);
adj = cell(Natom,1);
for b = 1:Nbond
    i = bondList(b,3);
    j = bondList(b,4);
    
    adj{i} = [adj{i}, j];
    adj{j} = [adj{j}, i];
end

% 获取angle信息
angleList = [];
angleID = 1;
for j = 1:Natom
    neighbors = adj{j};
    n = length(neighbors);
    
    for a = 1:n
        for b = a+1:n
            i = neighbors(a);
            k = neighbors(b);
            
            angleList(end+1,:) = [angleID, 1, i, j, k];
            angleID = angleID + 1;
        end
    end
end
Nangle = size(angleList,1);

% 获取dihedral信息
dihedralTemp = [];

for j = 1:Natom
    for k = adj{j}
        
        if k == j
            continue;
        end
        
        for i = adj{j}
            if i == k
                continue;
            end
            
            for l = adj{k}
                if l == j
                    continue;
                end
                
                % ===== canonical ordering =====
                if i < l
                    dihedralTemp(end+1,:) = [i j k l];
                else
                    dihedralTemp(end+1,:) = [l k j i];
                end
                
            end
        end
    end
end

% ===== 去重 =====
dihedralUnique = unique(dihedralTemp, 'rows');

% ===== 加上ID和type =====
Ndihedral = size(dihedralUnique,1);
dihedralList = [(1:Ndihedral)' , ones(Ndihedral,1), dihedralUnique];

% 生成文件头
writelines('# Generated by MATLAB',outputname)
writelines(sprintf('%d atom types',Tatom),outputname,'WriteMode','append')
writelines(sprintf('%d atoms',Natom),outputname,'WriteMode','append')
writelines(sprintf('%d bond types',1),outputname,'WriteMode','append')
writelines(sprintf('%d bonds', Nbond),outputname,'WriteMode','append')
writelines(sprintf('%d angle types',1),outputname,'WriteMode','append')
writelines(sprintf('%d angles', Nangle),outputname,'WriteMode','append')
writelines(sprintf('%d dihedral types',1),outputname,'WriteMode','append')
writelines(sprintf('%d dihedrals\n', Ndihedral),outputname,'WriteMode','append')

% 写入box信息
xbox = sprintf('%.4f %.4f xlo xhi',xlo, xhi);
writelines(xbox,outputname,'WriteMode','append')
ybox = sprintf('%.4f %.4f ylo yhi',ylo, yhi);
writelines(ybox,outputname,'WriteMode','append')
zbox = sprintf('%.4f %.4f zlo zhi\n',zlo, zhi);
writelines(zbox,outputname,'WriteMode','append')

% 写入Masses
writelines('Masses',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writelines('1 72',outputname,'WriteMode','append')

% 写入Atoms
writelines('',outputname,'WriteMode','append')
writelines('Atoms  # full',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writematrix(Atoms,outputname,"WriteMode","append",'FileType','text','Delimiter',' ')

% 写入Bonds
writelines('',outputname,'WriteMode','append')
writelines('Bonds',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writematrix(bondList,outputname,"WriteMode","append",'FileType','text','Delimiter',' ')

% 写入Angles
writelines('',outputname,'WriteMode','append')
writelines('Angles',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writematrix(angleList,outputname,"WriteMode","append",'FileType','text','Delimiter',' ')

% 写入Dihedrals
writelines('',outputname,'WriteMode','append')
writelines('Dihedrals',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writematrix(dihedralList,outputname,"WriteMode","append",'FileType','text','Delimiter',' ')